### ISSUE TITLE
New mintelf toolchain tries to locate shared libraries

### ISSUE THREAD

**Issue by th-otto** [freemint/m68k-atari-mint-gcc#24]
Just noticed that when linking with -Wl,-verbose:

```
attempt to open /opt/cross-mintelf/lib64/gcc/m68k-atari-mintelf/13.2.0/libgcc.so failed
attempt to open /opt/cross-mintelf/lib64/gcc/m68k-atari-mintelf/13.2.0/libgcc.a succeeded
```
Not a big deal as long as those *.so don't exist, but still an unneeded lookup, and something that previous toolchain did not do. Any idea what might be causing this?

**Comment by vinriviere** [comment]
Indeed, I noticed that yesterday. Not expected, because we want to turn off shared library support. So that's suboptimal. No idea what would happen if such library was found, certainly bad things.

**Comment by th-otto** [comment]
Must be some magic in the linker. My other toolchains (gcc-12 etc.) now behave the same.

**Comment by th-otto** [comment]
Found it. Fixed in https://github.com/freemint/m68k-atari-mint-binutils-gdb/commit/99cc418c887d4b5c44891c04dd344787671a5c4b

**Comment by vinriviere** [comment]
Ah. Good job.
