### ISSUE TITLE
Avoid include-fixed

### ISSUE THREAD

**Issue by vinriviere** [freemint/m68k-atari-mint-gcc#29]
I've recently updated my gcc build script to properly configure using `--with-sysroot`.
A side effect is that now the `include-fixed` directory is no longer empty.

```
$ ls -lR /usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed
/usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed:
total 28
drwxr-xr-x 2 root root  4096 oct.  26 21:05 bits
-rw-r--r-- 1 root root 18251 oct.  26 10:05 features.h
-rw-r--r-- 1 root root   750 oct.  26 10:05 README

/usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed/bits:
total 40
-rw-r--r-- 1 root root 37428 oct.  26 10:05 string2.h
```

Differences are:
```
$ diff -u /usr/m68k-atari-mintelf/include/features.h /usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed/features.h
@@ -507,7 +516,7 @@
 
 /* Decide whether we can define 'extern inline' functions in headers.  */
 #if __GNUC_PREREQ (2, 7) && defined __OPTIMIZE__ \
-    && !defined __OPTIMIZE_SIZE__ && !defined __NO_INLINE__
+    && !defined __OPTIMIZE_SIZE__ && !defined __NO_INLINE__ && (defined __extern_inline || defined __GNUC_GNU_INLINE__)
 # define __USE_EXTERN_INLINES	1
 # if (defined __GNUC_STDC_INLINE__ && __GNUC_STDC_INLINE__) || \
      defined __cplusplus || \
```

```
$ diff -u /usr/m68k-atari-mintelf/include/bits/string2.h /usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed/bits/string2.h
@@ -544,22 +553,9 @@
 /* Copy no more than N characters of SRC to DEST.  */
 #ifndef _HAVE_STRING_ARCH_strncpy
 # if defined _HAVE_STRING_ARCH_memset && defined _HAVE_STRING_ARCH_mempcpy
-#  define strncpy(dest, src, n) \
-  (__extension__ ({ char *__dest = (dest);				      \
-		    __builtin_constant_p (src) && __builtin_constant_p (n)    \
-		    ? (strlen (src) + 1 >= ((size_t) (n))		      \
-		       ? (char *) memcpy (__dest, src, n)		      \
-		       : (memset (__mempcpy (__dest, src, strlen (src)),      \
-				  '\0', n - strlen (src)),		      \
-			  __dest))					      \
-		    : strncpy (__dest, src, n); }))
+#  define strncpy(dest, src, n) __builtin_strncpy (dest, src, n)
 # else
-#  define strncpy(dest, src, n) \
-  (__extension__ (__builtin_constant_p (src) && __builtin_constant_p (n)      \
-		  ? (strlen (src) + 1 >= ((size_t) (n))			      \
-		     ? (char *) memcpy (dest, src, n)			      \
-		     : strncpy (dest, src, n))				      \
-		  : strncpy (dest, src, n)))
+#  define strncpy(dest, src, n) __builtin_strncpy (dest, src, n)
 # endif
 #endif
```
Basically:

1) Add  `&& (defined __extern_inline || defined __GNUC_GNU_INLINE__)`
I'm not familiar with those defines.

2) Replace complicated extensions with __builtin_strncpy()

We can agree that it's preferable to definitely fix the MiNTLib headers to avoid that GCC fixes them.

Is it safe to just apply GCC's proposed fixes to the MiNTLib?
Will it still work with older GCC?

**Comment by mikrosk** [comment]
It is (or used to be) even worse: https://github.com/mikrosk/m68k-atari-mint-build/blob/master-elf/Makefile#L299C62-L310

Basically during the cross-compilation some of the host include files were dragged in. From what you mention it seems that it has been fixed in the meantime and it actually provides valid content?

**Comment by vinriviere** [comment]
Er, as I never used `--with-sysroot` or similar before, so I never noticed. But current include-fixed content seems to be valid (even if I would be happy to get rid of it).

**Comment by th-otto** [comment]
> A side effect is that now the `include-fixed` directory is no longer empty.

Yes, these are the same file i get, too. In older toolchains, limits.h and syslimits.h where also stored there, but those are now in /usr/lib/gcc/m68k-atari-mintelf/13.2.0/include. But other files may end up there too, depending on what is already installed when you compile gcc. Eg. SDL/endian.h ends up there, too.

Generally i consider the include-fixed directory an ugly hack. It has precedence over the system include directory, that means everything that ends up there will be used, even if you later replace the fixed version in the system directory. So my script explicitly removes everything that does not belong there, and keeps only README, limits.h and syslimits.h.

> Replace complicated extensions with __builtin_strncpy()

Or remove that string2.h file altogether. It is actually not used at all: https://github.com/freemint/mintlib/blob/b77a680f1c944f587b9380e6c007814e6f81b0cd/include/string.h#L322-L359

**Comment by vinriviere** [comment]
OK, at least we can consider include-fixed files as warnings that something **may** be wrong in other package's includes.
But if GCC considers that something should be fixed, that's a hint. We should indeed improve the MiNTLib's includes to make GCC happy.

> So my script explicitly removes everything that does not belong there, and keeps only README, limits.h and syslimits.h.

OK. As you said that limits.h and syslimits.h were moved to standard gcc include in recent GCC, the include-fixed should only contain README. BTW, I also noticed that limits.h had moved, because before using --with-sysroot I had to fix my ugly hack for the PATH_MAX issue when moving to GCC 13.

> Generally i consider the include-fixed directory an ugly hack. It has precedence over the system include directory, that means everything that ends up there will be used, even if you later replace the fixed version in the system directory.

Sure.
So we can agree to keep include-fixed (almost) empty in binary distributions.

> So my script explicitly removes everything that does not belong there,

Yes, that's a solution.

Another solution, probably cleaner, would be to avoid running fixincludes at all. IIRC I disabled fixincludes in my early GCC 4.x builds, I don't remember well.

**Comment by th-otto** [comment]
> Another solution, probably cleaner, would be to avoid running fixincludes at all. IIRC I disabled fixincludes in my early GCC 4.x builds, I don't remember well.

IIRC, you have to run fixincludes in order to generate the limits.h and syslimits.h.

**Comment by vinriviere** [comment]
I've just tested compiling and installing GCC with `--disable-fixincludes`. Effects are:
- `/usr/lib/gcc/m68k-atari-mintelf/13.2.0/include` is still here and identical (even limits.h and syslimits.h)
- `/usr/lib/gcc/m68k-atari-mintelf/13.2.0/include-fixed/` is now empty (even README was removed)
- `/usr/lib/gcc/m68k-atari-mintelf/13.2.0/install-tools/include/README` has been removed

No other adverse effect.

From now on, I will build my binaries with `--disable-fixincludes`. So we can safely update the MiNTLib without fearing that GCC has cached something.

So this issue is partially fixed. GCC won't mess includes. But the MiNTLib may still need fixing. As this is is no more a GCC issue, I've opened 2 separate issues in MiNTLib:
https://github.com/freemint/mintlib/issues/62 for features.h
https://github.com/freemint/mintlib/issues/63 for bits/string2.h

Regarding to my GCC 13 binaries, we can close this issue. And let's continue the discussion about actual fixing on MiNTLib's issues.

**Comment by th-otto** [comment]
Did you also check other compiler versions with --disable-fixincludes? And do they generate the limits.h anywhere?

**Comment by vinriviere** [comment]
No, I only tested the current GCC 13.2.0. But from your previous statement, and my own experience, the include-fixed behaviour has changed in recent GCC versions (notably limits.h location). So this must be carefully checked in all relevant GCC versions.

NB: Regarding to my binaries, I plan to focus on mintelf GCC 13 and newer. I don't plan to upgrade my GCC 4.6.4 binaries, except than rebuilding the binaries as is for new operating systems.

**Comment by mikrosk** [comment]
This is indeed fixed. Closing.

**Comment by mikrosk** [comment]
Btw, I have pushed three commits into `gcc-7-mint` which fix `--disable-fixincludes`. The fix is surprisingly recent so it required multiple commits to be backported.

Not sure whether this will lead to another (mint) release, I just use it for testing my new scripts which share the same switches.
