### ISSUE TITLE
ASM_OUTPUT_COMMON: define common variable

### ISSUE THREAD

**Issue by vinriviere** [freemint/m68k-atari-mint-gcc#36]
I open this issue to understand the effects of the configuration variable `ASM_OUTPUT_COMMON`. It is used to define common variables.

Official GCC documentation:
https://gcc.gnu.org/onlinedocs/gccint/Uninitialized-Data.html#index-ASM_005fOUTPUT_005fCOMMON

Default m68k.h definition:
https://github.com/freemint/m68k-atari-mint-gcc/blob/0249dc16001f051ed8fe9e21d887972623869646/gcc/config/m68k/m68k.h#L833-L836

m68kelf.h definition:
https://github.com/freemint/m68k-atari-mint-gcc/blob/0249dc16001f051ed8fe9e21d887972623869646/gcc/config/m68k/m68kelf.h#L117-L120

We can see that both use the the `.comm` directive. But the argument is different. m68k.h uses the `ROUNDED` parameter, while m68kelf.h uses `SIZE`.

I plan to write testcases to examine actual effects.

**Comment by th-otto** [comment]
Well you are right, they are not really redundant because in case of ASM_OUTPUT_COMMON they are different. But since we already found that m68kelf.h is actually meant for embedded targets, and because we don't use it anymore, the override in mint.h should be removed, too (it wasn't there in older compilers). Also don't forget that newer gcc do not use common variables anymore by default.

**Comment by mikrosk** [comment]
So how mint.h should look like? If we revert 0249dc16, what should be then removed as it is not used?

**Comment by vinriviere** [comment]
Well, I'm still going to investigate the effects of `ASM_OUTPUT_COMMON`, without hurry. I will post the results here. Then I will use the most standard settings in my own mint.h (to be determined). But as @th-otto mentioned, newer gcc don't use common variables by default. So I guess that actual effect is very limited.

Regarding to mint.h for official FreeMiNT, default settings might be different. @th-otto pushed https://github.com/freemint/m68k-atari-mint-gcc/commit/0249dc16001f051ed8fe9e21d887972623869646 to revert to m68k-atari-mint behaviour.

**Comment by th-otto** [comment]
> But as @th-otto mentioned, newer gcc don't use common variables by default.

Yes, but we should still get that right. There are some older packages that are not yet aware of that, and you have to compile them with -fcommon or you get lots of duplicate symbol errors (mostly this is because variables are declared in header files without "extern").  Nano-X/microwindows (https://github.com/ghaerr/microwindows) is an example for this.

For the same reason (because it mostly affects older sources), i would argue to keep the old behaviour, even if that might waste a few bytes because the common size is rounded up. But it is already a pain sometimes to compile old sources with newer gcc, and having to investigate whether that change introduces problems would not make that better.

**Comment by vinriviere** [comment]
> I open this issue to understand the effects of the configuration variable ASM_OUTPUT_COMMON. 

Verdict: `ASM_OUTPUT_COMMON` has no effect because it is unused. Instead, `ASM_OUTPUT_ALIGNED_COMMON` defined by elfos.h takes precedence. Moreover, common variables aren't used by default (they use .bss instead).

Testcase:

com.c:
```
int g;
```

m68k-atari-mintelf-gcc -S -o - com.c
```
#NO_APP
        .file   "com.c"
        .text
        .globl  g
        .section        .bss
        .align  2
        .type   g, @object
        .size   g, 4
g:
        .zero   4
```
Result, with implicit `-fno-common`:
g is a 4-byte variable in the .bss section.

m68k-atari-mintelf-gcc -S -o - com.c -fcommon
```
#NO_APP
        .file   "com.c"
        .text
        .comm   g,4,2
```
Result:
g is a 4-byte variable in the COMMON pseudo-section. Like any int, it is by default aligned on 2-bytes.

Other test with nonstandard `-malign-int`:
m68k-atari-mintelf-gcc -S -o - com.c -fcommon -malign-int
```
#NO_APP
        .file   "com.c"
        .text
        .comm   g,4,4
 ```
Same result aligned o 4-bytes, as expected.

**Comment by vinriviere** [comment]
Documentation of `.comm`:
https://sourceware.org/binutils/docs/as/Comm.html

Those `.comm` statements are emitted from this code:

https://github.com/freemint/m68k-atari-mint-gcc/blob/4598322acf7f9abe94721449c100f782185f05df/gcc/varasm.c#L1982-L2002

We can see that if `ASM_OUTPUT_ALIGNED_COMMON` is defined, it takes precedence over `ASM_OUTPUT_COMMON`.

Note that `ASM_OUTPUT_ALIGNED_COMMON` produces a `.comm` statement with 3 parameters, while `ASM_OUTPUT_COMMON` produces a `.comm` statement with only 2 parameters. This is another clue that `ASM_OUTPUT_COMMON` isn't used in our case.

**Comment by vinriviere** [comment]
Situation is the same for `.lcomm` statement with `ASM_OUTPUT_LOCAL` and `ASM_OUTPUT_ALIGNED_LOCAL`.
https://github.com/freemint/m68k-atari-mint-gcc/blob/4598322acf7f9abe94721449c100f782185f05df/gcc/varasm.c#L1944-L1965

**Comment by vinriviere** [comment]
Conclusion:
`ASM_OUTPUT_COMMON` has no effect because it is unused.
Instead, definition of `ASM_OUTPUT_ALIGNED_COMMON` from elfos.h takes precedence.
Furthermore, common variables are only used when compiling with `-fcommon`, which is now unusual.

So it's pointless doing anything with `ASM_OUTPUT_COMMON` as it is unused.
The good practice is just to ignore that parameter.

Initially, I fetched that code from m68kelf.h:
https://github.com/freemint/m68k-atari-mint-gcc/blob/4598322acf7f9abe94721449c100f782185f05df/gcc/config/m68k/m68kelf.h#L115-L125
But as it is unused, that's a nonsense.

So @th-otto's commit https://github.com/freemint/m68k-atari-mint-gcc/commit/0249dc16001f051ed8fe9e21d887972623869646 is finally good, as it removes unused code.

End of story, there is no more to do.
