### ISSUE TITLE
gcc4: Internal compiler error when compiling mintlib's regex.c

### ISSUE THREAD

**Issue by th-otto** [freemint/m68k-atari-mint-gcc#40]
Some time ago i activated compiling the debug variants of mintlib when using the mintelf toolchain.  Now, when using gcc 4.6.4, i get

`../posix/regex.c:5172:1: internal compiler error: in fixup_reorder_chain, at cfglayout.c:877`

This is not specific to the mintelf toolchain, it also happens when using the normal compiler with the same flags. The difference with the flags is using -O2 for the release build, and -O for the debug builds. It also only happens with gcc 4.6.4, all other compilers are fine. It also compiles fine with gcc 4.6.4 when using either -O0 or -O2. Any idea what was fixed in later gcc versions?

The behaviour can be tested by using
`
m68k-atari-mint-gcc -Wall -Werror -Wstrict-prototypes -Wmissing-prototypes -Wold-style-declaration -Wold-style-definition -Wdeclaration-after-statement -fgnu89-inline -nostdinc -I../posix -I.. -I../include -I../mintlib -I../stdlib   -DHAVE_CONFIG_H -D_LIBC -D_REENTRANT  -c ../posix/regex.c -o regex.o -I$(cat ../includepath) -O1
`

**Comment by mikrosk** [comment]
Oh man, I'm afraid we are on our own here, nobody would ever open this, if reported in their bugzilla.

One could git bisect it but... ehem. Perhaps just make a rule in mintlib to compile this file with `-O0` for debug builds, if you think it's useful.

**Comment by th-otto** [comment]
Yes, i worked around that now in the source. I've also checked that its not a fault of my port, vincents compiler gives the same ICE.

But im still curious to understand the reason. Who knows what other projects may trigger this.

Attached is a preprocessed version of the file, which can be compiled using just -O1.

[regex_i.c.txt](https://github.com/freemint/m68k-atari-mint-gcc/files/15140867/regex_i.c.txt)

**Comment by th-otto** [comment]
> One could git bisect it but... ehem

I actually did  that, and using that found https://github.com/freemint/m68k-atari-mint-gcc/commit/7a76df7f955128bb5c70d67bf428b8996ad48d42

Just as reminder, if someone ever has to do something similar:

- since you don't want to port the mint patch to each and every revision that is checked out during bisect, i started with the release/gcc-4.9 branch, and configured it for bare m68k-elf. For that you will also need the binutils for m68k-elf.
- Because i was trying to find the commit that fixed something (and not a regression), you have to mark the revisions that fail as "good", and the ones that work as "bad".
- in this case, after configuring the compiler, it is sufficient to do just "make all-gcc". You can then invoke the compiler using 
`$ <build-dir>/./gcc/xgcc -B<build-dir>/./gcc/ -O1 -c regex_i.c
`
Building just the c-compiler and nothing else takes around 2min on my linux box

Attached are the two patches that result from this. The first one was previous in history, but patched the same location. Since it was also a fix, i decided just to apply that first.

@vinriviere : in case you ever recompile your gcc 4.6.4 toolchain (eg. for newer ubuntu version) maybe you want to include them in your builds

[0001-re-PR-rtl-optimization-58662-wrong-code-at-O2-for-du.patch.txt](https://github.com/freemint/m68k-atari-mint-gcc/files/15146196/0001-re-PR-rtl-optimization-58662-wrong-code-at-O2-for-du.patch.txt)
[0002-re-PR-rtl-optimization-52714-ICE-in-fixup_reorder_ch.patch.txt](https://github.com/freemint/m68k-atari-mint-gcc/files/15146200/0002-re-PR-rtl-optimization-52714-ICE-in-fixup_reorder_ch.patch.txt)

**Comment by mikrosk** [comment]
Nice detective work. :)

> Because i was trying to find the commit that fixed something (and not a regression), you have to mark the revisions that fail as "good", and the ones that work as "bad".

Actually you can do this automatically but I don't bother: https://stackoverflow.com/questions/15407075/how-could-i-use-git-bisect-to-find-the-first-good-commit.

**Comment by mikrosk** [comment]
Huh, not sure what my commit didn't auto-close this issue. Anyway, I have pushed both commits into `gcc-4_6-mint` branch.
