### ISSUE TITLE
Status of GCC 5.x or 6.x or 7.x ?

### ISSUE THREAD

**Issue by atic-atac** [freemint/m68k-atari-mint-gcc#6]
Can anyone update me here on what's stable now ?

**Comment by ps68060** [comment]
I can see that 7.2 is listed as a release.

https://github.com/freemint/m68k-atari-mint-gcc/releases

Before I try to upgrade from 4.6.4 what else do I need to update ?

**Comment by mikrosk** [comment]
See https://github.com/freemint/m68k-atari-mint-gcc/releases/tag/gcc-7_3_0-mint.
